name: Lint code

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Run pre-commit
        run: |
          pip install "pre-commit==3.5.0"
          pre-commit run -a
      - name: Run nox
        run: |
          pip install "nox==2024.4.15"
          nox -s lint
